- webui/src/App.js
- webui/src/components/Collections.js
- webui/src/components/SideNav.js
- webui/src/styles/common.css
- webui/src/styles/global.scss
- webui/src/styles/view-ui.css
* Created a component to show the collection list.
* The "Create Collection" can be set as a separated page or a modal (if it doesn't have a lot of options).
* This same code structure can be used for the other models later (users, teams, files).
* Some elements can be disabled in case we dont need them (like the filter and floating menus in the table).
* There a bug in the pagination that makes it jump to page 11 when we click to go to the next page. I will check if it has a  fix in the carbon library.
> View collection page

- backend/main.py
- backend/rag_solution/data_ingestion/ingestion.py
- backend/rag_solution/router/search_router.py
- backend/rag_solution/schemas/search_schema.py
- backend/rag_solution/services/collection_service.py
- backend/rag_solution/services/search_service.py
- webui/src/components/common/SearchInterface.js
Make sure async processing is properly regarded
Bubble up exceptions to prevent further steps from execution and leading to "exception avalanche"
> Document processing flow adjustments

- Makefile
- backend/Dockerfile.backend
- backend/Dockerfile.test
- webui/Dockerfile.frontend
- webui/package-lock.json
modified the following files:
Makefile:
1. Add CONTAINER_CLI := podman to ensure we have a variable for container cli
2. Added new build target "sync-frontend-deps" so frontend dependencies can be refreshed (if package.json is modified)
3. Added missing "@ sign in this line: @if [ "$(VECTOR_DB)" = "milvus" ]
4. Modified test targets that were building twice
backend/Dockerfile.backend
1. Modified the file to stop copying entire .venv
webui/Dockerfile.frontend
1. combined environment variable declaration
2. changed to 'npm install ci'
> fix build issues in Dockerfiles and Makefile

- backend/auth/oidc.py
- backend/core/config.py
- backend/rag_solution/router/auth_router.py
- webui/default.conf
- webui/src/config/config.js
> fixed token exchange and login

- backend/rag_solution/data_ingestion/pdf_processor.py
- backend/vectordbs/milvus_store.py
adjust `pdf_processor.py` to work with `get_embeddings` function using watsonx.ai SDK which returns a list of embeddings.
to be able to ingest documents - `EMBEDDING_MODEL` environment variable must be set
example : 
`EMBEDDING_MODEL=sentence-transformers/all-minilm-l6-v2`
> Ingest issue 31

- backend/rag_solution/generation/generator.py
- backend/rag_solution/pipeline/pipeline.py
- backend/rag_solution/retrieval/retriever.py
- backend/rag_solution/router/search_router.py
- backend/rag_solution/schemas/search_schema.py
- backend/rag_solution/services/search_service.py
- backend/tests/data_ingestion/test_ingestion.py
- backend/tests/pipeline/test_pipeline.py
- backend/tests/retrieval/test_factories.py
- backend/tests/retrieval/test_retriever.py
- backend/tests/vectordbs/test_base_store.py
- backend/vectordbs/chroma_store.py
- backend/vectordbs/milvus_store.py
- backend/vectordbs/pinecone_store.py
- backend/vectordbs/vector_store.py
- backend/vectordbs/weaviate_store.py
- webui/src/api/api.js
- webui/src/components/SearchInterface.css
- webui/src/components/common/SearchInterface.js
- webui/src/config/config.js
> edited several files to ensure search works

- webui/src/App.js
- webui/src/components/LoginPage.js
- webui/src/components/collection/Collection.css
- webui/src/components/collection/Collection.js
- webui/src/components/collection/CollectionViewer.js
- webui/src/components/layout/SideNav.js
- webui/src/styles/view-ui.css
Change the collections list to add the option to see it as a table or tiles.
Create new collection working. The other operations will be set on another PR.
> add option to see collections as tiles

- backend/rag_solution/router/search_router.py
- backend/rag_solution/services/search_service.py
Fixed search issues.
1. backend/rag_solution/services/search_service.py - made `search async`. deleted `search_stream` redundant method. 
2. backend/rag_solution/router/search_router.py - removed search_stream endpoint that is no longer needed.
> Fix async issues in search router and search service

- backend/core/config.py
- backend/rag_solution/generation/generator.py
- backend/rag_solution/services/question_service.py
- backend/vectordbs/utils/watsonx.py
Fixed concurrency to stuff multiple calls to watsonx
> added concurrency to generate questions

- webui/src/components/layout/SideNav.js
> Sidenav icons

- Makefile
Changes to Makefile:
1. Make test more flexible so it doesn't automatically rebuild backend container
2. Added target for check_containers
3.
> Modified test target to be more flexible

- backend/rag_solution/generation/providers/__init__.py
- backend/rag_solution/generation/providers/anthropic.py
- backend/rag_solution/generation/providers/base.py
- backend/rag_solution/generation/providers/factory.py
- backend/rag_solution/generation/providers/openai.py
- backend/rag_solution/generation/providers/watsonx.py
- Added support for providers: Anthropic, OpenAI, WatsonX.
- Organized provider logic into separate modules.
- Improved modularity and scalability of provider management.
> Add new providers architecture with Anthropic, OpenAI, WatsonX providers

- backend/core/config.py
Fixes #85 
https://github.com/manavgup/rag_modulo/issues/85
Modified config.py to have two classes:
- previous settings is now LegacySettings
- minimal core credentials required to start the app as new Settings
- Removed non-essential settings that can be managed at runtime
- Added proper validation using Pydantic
- Added comprehensive documentation
no longer a breaking PR
> refactor: Simplify core configuration to essential settings fixes #85

- backend/core/config.py
- backend/rag_solution/docs/configuration.md
- backend/tests/conftest.py
- backend/tests/test_core_config.py
> started baselining the configuration management system

- backend/core/custom_exceptions.py
- backend/rag_solution/models/llm_parameters.py
- backend/rag_solution/repository/llm_parameters_repository.py
- backend/rag_solution/schemas/llm_parameters_schema.py
- backend/rag_solution/services/llm_parameters_service.py
- backend/tests/conftest.py
- backend/tests/test_llm_parameters.py
1. Schema Layer (llm_parameters_schema.py):
Pydantic v2 models with proper validation
Model validators for cross-field validation
Computed fields with proper exclusion
Strong type checking with Annotated fields
Rich documentation and examples
2. Database Layer (llm_parameters.py):
SQLAlchemy 2.0 model with Mapped types
Field validation with proper error messages
Automatic timestamp handling
Proper nullable field handling
3. Repository Layer (llm_parameters_repository.py):
CRUD operations with transaction handling
Strong typing throughout
Proper error handling with custom exceptions
Default parameter set management
4. Service Layer (llm_parameters_service.py):
Business logic with validation
Custom exceptions for error handling
Comprehensive logging
Parameter set management
5. Other changes …
> Added model, schema, repository, service, and test file

- backend/core/custom_exceptions.py
- backend/rag_solution/docs/prompt_templates.md
- backend/rag_solution/models/prompt_template.py
- backend/rag_solution/repository/prompt_template_repository.py
- backend/rag_solution/schemas/prompt_template_schema.py
- backend/rag_solution/services/prompt_template_service.py
- backend/tests/test_prompt_template.py
The prompt template system has been fully implemented with:
1. Core Components:
- SQLAlchemy model with built-in examples
- Pydantic schemas with validation
- Repository and service layers
- Comprehensive test suite
2. Documentation:
- Technical architecture
- Security considerations
- Integration guidelines
- Deployment best practices
- Future roadmap
The system provides a robust foundation for managing prompt templates in the RAG solution, with support for multiple LLM providers and flexible customization options.
> Add prompt template model, schema, repository, service, and test files

- backend/core/custom_exceptions.py
- backend/rag_solution/docs/provider_configuration.md
- backend/rag_solution/models/provider_config.py
- backend/rag_solution/repository/provider_config_repository.py
- backend/rag_solution/schemas/provider_config_schema.py
- backend/rag_solution/services/provider_config_service.py
- backend/tests/test_provider_config.py
The provider configuration system is now complete with:
1. Strong Type Safety:
- LLMParametersCreate for parameter configuration
- PromptTemplateCreate for template configuration
- Proper error types and handling
2. Integration Points:
- Direct integration with LLM parameters system
- Optional prompt template integration
- Proper error propagation
3. Key Features:
- Provider model registration with typed parameters
- Template management
- Status tracking
- Verification system
4. Implementation Details:
- SQLAlchemy models with proper relationships
- Pydantic schemas for request/response handling
- Repository pattern for data access
- Service layer for business logic
- The system allows for type-safe configuration of LLM providers while maintaining flexibility through optional prompt …
> add model, schema, repo, service, and test for llm provider configuration

- backend/rag_solution/repository/llm_parameters_repository.py
- backend/rag_solution/repository/pipeline_repository.py
- backend/rag_solution/schemas/llm_parameters_schema.py
- backend/rag_solution/schemas/pipeline_schema.py
- backend/rag_solution/services/llm_parameters_service.py
- backend/rag_solution/services/pipeline_service.py
Enhance LLM Pipeline and Configuration Management
This PR improves the LLM pipeline functionality:
- Enhances LLM parameters repository with better validation
- Adds provider information to pipeline configuration
- Improves collection access validation in pipeline
- Adds detailed execution metadata and logging
- Implements proper error handling throughout pipeline
- Adds pipeline validation checks
Testing:
- Verified pipeline execution with various configurations
- Tested error handling in different pipeline stages
- Validated provider integration and parameter handling
- Confirmed proper metadata collection and logging
Dependencies: feat/data-management
> feat(llm): enhance LLM parameters and pipeline handling

- backend/tests/conftest.py
- backend/tests/service/test_question_service.py
- backend/tests/service/test_search_service.py
Improve Test Coverage and Testing Infrastructure
This PR enhances the testing infrastructure:
- Adds vector store fixture for consistent testing
- Enhances test configuration with better defaults
- Improves test coverage across core components
- Adds comprehensive error case testing
- Improves test maintainability and organization
- Implements better test logging and debugging
Testing:
- Verified test coverage improvements
- Validated vector store fixture functionality
- Confirmed error case coverage
- Tested debugging improvements
Dependencies: feat/llm-pipeline
> feat(test): enhance test coverage and fixtures

- webui/src/App.css
- webui/src/App.js
- webui/src/components/layout/Footer.js
- webui/src/components/layout/Header.css
- webui/src/components/layout/Header.js
- webui/src/components/layout/SideNav.css
- webui/src/components/layout/SideNav.js
- webui/src/contexts/AuthContext.js
* Page height self-adjustment 
* Footer always in the bottom
* Cleaned menu code and fixed names and items alignment
> Fix height, items alignment and menus

- claudeDev_Docs/ROADMAP.md
- claudeDev_Docs/designDocumentSummary.md
- claudeDev_Docs/devNotes.md
- claudeDev_Docs/sprintDocs/01_projectSetup.md
- claudeDev_Docs/sprintDocs/02_backendSetup.md
- claudeDev_Docs/sprintDocs/03_frontendStructure.md
- claudeDev_Docs/sprintDocs/04_coreFunctionality.md
- claudeDev_Docs/sprintDocs/05_dataIntegration.md
- claudeDev_Docs/sprintDocs/06_refinementAndPolish.md
- claudeDev_Docs/sprintDocs/07_deploymentPreparation.md
- Update project status to reflect current development phase
- Add detailed ROADMAP.md with development milestones
- Update sprint documentation to reflect completed work
- Document current architecture and implementation status
- Add development notes and technical decisions
> docs: Update project status and add comprehensive roadmap

- .github/workflows/ci.yml
- .github/workflows/test-and-issue.yml
- .github/workflows/watsonx-benchmarks.yml
- ISSUES/ci-cd-pipeline-failures.md
This PR addresses **GitHub Issue #113** by fixing all the deprecated GitHub Actions that were causing automatic workflow failures.
The CI/CD pipeline was failing because it was using deprecated GitHub Actions versions:
-  → **DEPRECATED** (April 16, 2024)
-  → **DEPRECATED** (April 16, 2024)  
-  → **DEPRECATED** (April 16, 2024)
-  → **DEPRECATED** (April 16, 2024)
- **CI/CD Pipeline** (): Updated all v3 actions to v4
- **Test and Issue Creation** (): Updated all v3 actions to v4
- **WatsonX Benchmarks** (): Updated all v3 actions to v4
- Replaced  with modern 
- Updated 
Usage:  docker compose [OPTIONS] COMMAND
Define and run multi-container applications with Docker
Options:
--all-resources              Include all resources, even those not used by services
--ansi string …
> Fix CI/CD Pipeline Failures - Update Deprecated GitHub Actions

- Makefile
Implements Phase 1 of the Makefile improvements outlined in #139.
- **Fixed misleading import sorting message**: Updated `format-ruff` target to accurately describe its functionality
- **Added actual import sorting**: New `format-imports` target uses ruff's import sorting capabilities (`--select I --fix`)
- **Added import validation**: New `check-imports` target validates import order without making changes
- **Added developer workflow target**: New `quick-check` target runs format-check + check-imports + lint-ruff for rapid feedback
- **Updated format target**: Now includes both formatting and import sorting
- **Enhanced virtual environment management**: Proper venv setup with consistent poetry execution
- **Updated help documentation**: All new targets documented in help output
- `make …
> feat: Implement Phase 1 Makefile improvements

- Makefile
Completes **Phase 3** of the Makefile improvements outlined in #139, adding comprehensive dependency management, documentation generation, and UV package manager evaluation.
- **`make check-deps`** - Identifies outdated dependencies with version comparison
- **`make check-deps-tree`** - Visualizes complete dependency hierarchy
- **`make export-requirements`** - Exports Poetry dependencies to requirements.txt files
- **`make docs-generate`** - Creates API documentation using pydoc
- **`make docs-serve`** - Serves documentation locally at http://localhost:8080
- Provides quick access to module documentation for developers
- **`make uv-install`** - Installs UV package manager (Rust-based, 10-100x faster)
- **`make uv-sync`** - Syncs dependencies with UV
- **`make uv-export`** - Exports …
> feat: Implement Phase 3 Makefile improvements - Dependencies, Docs & UV

- backend/rag_solution/core/dependencies.py
- backend/rag_solution/router/collection_router.py
- backend/rag_solution/router/user_routes/collection_routes.py
- backend/rag_solution/router/user_routes/file_routes.py
- backend/rag_solution/router/user_routes/llm_routes.py
- backend/rag_solution/router/user_routes/pipeline_routes.py
- backend/rag_solution/router/user_routes/prompt_routes.py
- backend/rag_solution/services/collection_service.py
- backend/rag_solution/services/question_service.py
Refactor large methods that violate Single Responsibility Principle by breaking them down into focused helper methods.
1. **QuestionService.suggest_questions** (117 lines → 5 helper methods):
- `_setup_question_generation`: Initialize provider and combine text chunks
- `_generate_questions_from_texts`: Process text batches through LLM
- `_extract_questions_from_responses`: Parse LLM responses into questions
- `_process_generated_questions`: Filter, deduplicate, and rank questions
- `_store_questions`: Persist questions to database
2. **CollectionService.process_documents** (106 lines → 5 helper methods):
- `_process_and_ingest_documents`: Handle document ingestion and error handling
- `_extract_document_texts`: Extract and validate text chunks from documents
- …
> Phase 7: Large Method Breakdowns - Defensive Programming

- .env.ci
- .github/workflows/ci.yml
- .gitignore
- backend/rag_solution/router/health_router.py
- docker-compose-infra.yml
- docker-compose.yml
This PR fixes critical CI/CD pipeline failures by addressing two main issues:
- Added `.env.ci` file with mock OIDC and WatsonX values for CI testing
- Resolves Docker Compose warnings about missing environment variables
- Uses mock values that are safe to commit to GitHub
- Fixed etcd image version from `bitnami/etcd:latest` to `bitnami/etcd:3.5.9`
- Resolves "manifest not found" error that was breaking container startup
- **Added `.env.ci`**: Mock environment variables for CI testing
- **Updated `.gitignore`**: Allow `.env.ci` while keeping real `.env` files private
- **Fixed `docker-compose-infra.yml`**: Use specific etcd image version
- ✅ Fixes CI failures in all open PRs
- ✅ Enables automated testing and deployment
- ✅ Unblocks development workflow
- ✅ No security risk (mock values …
> fix: Add CI environment variables and fix etcd image

- backend/Dockerfile.test
- backend/rag_solution/data_ingestion/txt_processor.py
- backend/rag_solution/doc_utils.py
- backend/rag_solution/generation/providers/watsonx.py
- backend/rag_solution/models/collection.py
- backend/rag_solution/models/llm_parameters.py
- backend/rag_solution/models/question.py
- backend/rag_solution/models/user_collection.py
- backend/rag_solution/models/user_team.py
- backend/rag_solution/schemas/llm_provider_schema.py
- backend/rag_solution/services/pipeline_service.py
- backend/rag_solution/services/search_service.py
- backend/rag_solution/services/user_provider_service.py
- backend/tests/api/test_search_debug_edge_cases.py
- backend/tests/fixtures/collections.py
- backend/tests/fixtures/files.py
- backend/tests/fixtures/llm.py
- backend/tests/fixtures/services.py
- backend/vectordbs/milvus_store.py
- Implemented missing functionality to make existing tests pass
- Fixed document ID consistency issues in TxtProcessor
- Enhanced test fixtures for better integration testing
- **Data Consistency Validation Tests** (4/4 criteria):
- Document count matching between DB and vector store
- Collection names consistent across systems
- Retrieved document IDs exist in metadata
- No orphaned documents in vector store
- **Error Handling Validation Tests** (4/4 criteria):
- Empty collection returns graceful message
- Invalid collection ID returns 404/500
- Malformed query returns 400 with clear error
- Vector store connection failure returns 503
- **Search Results Display Validation** (2/2 criteria):
- Results display formatting
- Document indexing verification
- **Document Retrieval Validation** …
> feat: Complete Issue #160 - Debug search functionality and implement comprehensive test coverage

- docs/tests/API_ROUTER_SERVICE_OVERLAP_ANALYSIS.md
- docs/tests/CI_CD_WORKFLOW_MODIFICATIONS.md
- docs/tests/FIXTURE_CENTRALIZATION_STRATEGY.md
- docs/tests/FIXTURE_MIGRATION_MAPPING.md
- docs/tests/IMPLEMENTATION_ROADMAP.md
- docs/tests/MASTER_TEST_OPTIMIZATION_ROADMAP.md
- docs/tests/SERVICE_DIRECTORY_DUPLICATION_ANALYSIS.md
- docs/tests/TEST_FILE_CONSOLIDATION_PLAN.md
- docs/tests/TEST_INFRASTRUCTURE_REFACTORING_PLAN.md
- Add MASTER_TEST_OPTIMIZATION_ROADMAP.md with unified strategy
- Add FIXTURE_CENTRALIZATION_STRATEGY.md for fixture management
- Add TEST_FILE_CONSOLIDATION_PLAN.md for file organization
- Add CI_CD_WORKFLOW_MODIFICATIONS.md for pipeline optimization
- Add SERVICE_DIRECTORY_DUPLICATION_ANALYSIS.md for critical issues
- Add API_ROUTER_SERVICE_OVERLAP_ANALYSIS.md for functional overlap
- Add IMPLEMENTATION_ROADMAP.md for detailed timeline
- Add FIXTURE_MIGRATION_MAPPING.md for fixture migration
Addresses Issues #187 and #176 with comprehensive test infrastructure refactoring plan.
> 📚 Add comprehensive test optimization roadmap

- README.md
- backend/rag_solution/services/conversation_service.py
- docs/features/index.md
- docs/getting-started.md
- docs/index.md
- docs/roadmap.md
- docs/troubleshooting/common-issues.md
- mkdocs.yml
This PR implements comprehensive documentation enhancements to align RAG Modulo with the high standards demonstrated by the IBM MCP Context Forge project.
- **Professional Header**: Added badges, status indicators, and clear project description
- **Quick Start Section**: Streamlined getting started experience with multiple options
- **Enhanced Feature Overview**: Comprehensive feature showcase with visual elements
- **Improved Installation Guide**: Multiple installation options with clear instructions
- **Better Troubleshooting**: Common issues and solutions with collapsible sections
- **Contributing Guidelines**: Clear contribution process and development setup
- **Comprehensive Navigation**: Well-organized documentation hierarchy
- **Enhanced Content**: Detailed guides for all aspects …
> 📚 Documentation Enhancement: Align with MCP Context Forge Standards

- .github/AGENTS_README.md
- backend/AGENTS.md
- backend/rag_solution/AGENTS.md
- backend/rag_solution/models/AGENTS.md
- backend/rag_solution/repository/AGENTS.md
- backend/rag_solution/router/AGENTS.md
- backend/rag_solution/schemas/AGENTS.md
- backend/rag_solution/services/AGENTS.md
- frontend/AGENTS.md
- frontend/src/components/AGENTS.md
This PR adds a comprehensive AGENTS.md documentation system throughout the codebase to provide contextual information for AI development tools (Claude, Copilot) and human developers.
**This is a focused PR split from #265 containing ONLY documentation files.**
- ✅ `.github/AGENTS_README.md` - Team guide for using and maintaining the system
- ✅ `backend/AGENTS.md` - Backend architecture overview
- ✅ `backend/rag_solution/AGENTS.md` - Main application package guide
- ✅ `backend/rag_solution/services/AGENTS.md` - Service layer patterns
- ✅ `backend/rag_solution/models/AGENTS.md` - SQLAlchemy ORM models
- ✅ `backend/rag_solution/schemas/AGENTS.md` - Pydantic schemas
- ✅ `backend/rag_solution/router/AGENTS.md` - FastAPI endpoints
- ✅ `backend/rag_solution/repository/AGENTS.md` - Data access …
> docs: Add AGENTS.md documentation system
